controllers/user.py
from flask import  Blueprint, request, render_template, jsonify
from module.db import User, addUser
from module.auth import jwt
from flask_jwt_extended import (
    create_access_token,
    set_access_cookies,
    unset_jwt_cookies
)
import datetime

user = Blueprint('user', __name__)

@user.route('/register', methods = ['GET'])
def registerGet():
    return render_template('register_page.html', msg = request.args.get('msg'))

@user.route('/register', methods=['POST'])
def registerPost():
    searchEmail = User.query.filter(User.user_email==request.form['email']).first()
    # searchData = User.query.filter(User.user_email == request.form['user_email']).first()
    if not searchEmail:             # if email doesn't exist, build one
        user = User(   
            user_email = request.form['email'],
            user_password = request.form['password'],
        )
        addUser(user)
        return jsonify(msg = 'Register successfully'), 200
    else:
        return jsonify(msg = 'Email already exists'), 200

@user.route('/login', methods=['GET'])
def loginGet():
    return render_template('login_page.html', msg = request.args.get('msg'))

@user.route('/login', methods=['POST'])   
def loginPost():
    try:
        searchData = User.query.filter(User.user_email == request.form['user_email']).first()
        if searchData:
            if searchData.user_password == request.form['user_password']:
                # Make a response that put access_token into headers
                response = jsonify({"msg": "login successful"})
                access_token = create_access_token(identity={'user_id':searchData.user_id}, expires_delta=datetime.timedelta(minutes=60))
                set_access_cookies(response, access_token)
                return response
            else:
                return jsonify(msg = 'Incorrect password\n'), 200
        else:
            return jsonify(msg = 'No such user was found\n'), 200
    except:
        return jsonify(msg = 'Due to using free tier of database, Maybe you should refresh page')
    
@user.route("/logout", methods=["POST"])
def logout_with_cookies():
    response = jsonify({"msg": "logout successful"})
    unset_jwt_cookies(response)
    return response

controllers/workshop.py
from flask import  Blueprint, request, render_template, jsonify
from module.app import app
from module.db import Video, addVideo, updateVideo
from module.auth import jwt
from flask_jwt_extended import (
    jwt_required,
    get_jwt_identity
)
from werkzeug.utils import secure_filename
import os
import datetime
import json

workshop = Blueprint('workshop', __name__)

@workshop.route('/', methods=['GET'])
@jwt_required()
def workshopGet():
    try:
        payload = get_jwt_identity()
        dbVideos = Video.query.filter(Video.video_owner == payload['user_id'])
        workshopVideos = []
        userVideos = []
        for row in dbVideos:
            if row.is_converted:
                workshopVideos.append( [row.video_url, row.srt_url] )
            else: 
                userVideos.append( [row.video_url, row.srt_url] )
        return render_template('workshop_page.html', user_videos = userVideos, workshop_videos = workshopVideos)
    except:
        return jsonify(msg = 'Since free tier of database would shut down every 30 minutes, maybe you should refresh the page')


@workshop.route('/upload-video', methods=['POST'])
@jwt_required()
def upload():
    try:
        file = request.files['file_from_user']
        time_now = datetime.datetime.now().strftime('%Y%m%d-%H%M%S_')
        file_name = time_now + secure_filename(file.filename)
        file_path = os.path.join( app.config['USER_FOLDER'], file_name)
        payload = get_jwt_identity()
        file.save(file_path)
        video = Video(
            video_name  = file_name,
            video_url   = file_path,
            video_owner = payload['user_id']
        )
        addVideo(video)
        return jsonify(msg = 'Upload successfully'), 200
    except:
        return jsonify(msg = 'Since free tier of database would shut down every 30 minutes, maybe you should refresh the page')

@workshop.route('/add-subtitles', methods=['POST'])
@jwt_required()
def add_subtitles():
    try:
        video_path = json.loads(request.data)
        video_name = video_path.split('/')[1].split('.')[0]
        files =  os.listdir(app.config['SRT_FOLDER'])
        if (f'{video_name}.srt') in files:
            msg = 'SRT already exist'
        else:
            msg = 'Successfully add subtitles'
            os.system(f'autosub -S zh-TW -D zh-TW -o ./srtFiles/{video_name}.srt ./{video_path}')
            video_to_update = Video.query.filter(Video.video_url == video_path).first()
            video_to_update.srt_url = f'srtFiles/{video_name}.srt'
            updateVideo()
        return jsonify(msg)
    except:
        return jsonify(msg = 'Since free tier of database would shut down every 30 minutes, maybe you should refresh the page')

@workshop.route('/update-subtitles', methods=['POST'])
def update_subtitles():
    try:
        videoPath = request.form.get("video_path")
        videoName_wo_ext = videoPath.split('/')[1].split('.')[0]
        with open(f'./srtFiles/{videoName_wo_ext}.srt', 'r') as f:
            content = f.readlines()
            index = 1
            for i in range(2, len(content), 4):
                content[i] = f'{request.form[str(index)]}\n'
                index += 1
        content = ''.join(content)
        with open(f'./srtFiles/{videoName_wo_ext}.srt', 'w') as f:
            f.write(content)

        return jsonify('Update subtitles successfully')
    except:
        return jsonify(msg = 'Since free tier of database would shut down every 30 minutes, maybe you should refresh the page')
@workshop.route('/merge-subtitles', methods=['POST'])
def merge_subtitles():
    try:
        video_path = json.loads(request.data)
        video_to_update = Video.query.filter(Video.video_url == video_path).first()
        video_name = video_path.split('/')[1].split('.')[0]
        
        if video_to_update.is_converted:
            os.system(f'rm {video_path}')
            os.system(f"ffmpeg -y -i userFiles/{video_name}.mp4 -vf 'subtitles=./srtFiles/{video_name}.srt' ./workshopFiles/{video_name}.mp4")
        else:
            video_to_update.video_url = 'workshopFiles/' + video_path.split('/')[1]
            video_to_update.is_converted = True
            updateVideo()
            os.system(f"ffmpeg -y -i {video_path} -vf 'subtitles=./srtFiles/{video_name}.srt' ./workshopFiles/{video_name}.mp4")

        # os.system(f'rm {video_path}')
        return jsonify('Merge Successfully')
    except:
        return jsonify(msg = 'Since free tier of database would shut down every 30 minutes, maybe you should refresh the page')


@workshop.route('/edit-subtitles/<videoDirectory>/<videoName>', methods=['GET'])
def edit_subtitles(videoDirectory, videoName):
    try:
        videoPath = videoDirectory + '/' + videoName
        videoName_wo_ext = videoName.split('.')[0]
        with open(f'srtFiles/{videoName_wo_ext}.srt', 'r', encoding='UTF-8') as f:
            lines = []
            while True:
                line = []
                [line.append(f.readline().strip()) for i in range(3)]
                lines.append(line)
                if not f.readline():
                    break
        return render_template('edit_subtitles.html', lines = lines, videoPath = videoPath)
    except:
        return jsonify(msg = 'Since free tier of database would shut down every 30 minutes, maybe you should refresh the page')

main.py
from module.app import app
from flask import redirect, url_for, send_file, send_from_directory
from controllers.user import user
from controllers.workshop import workshop

app.config['USER_FOLDER'] = 'userFiles/'
app.config['SRT_FOLDER'] = 'srtFiles/'
app.config['WORKSHOP_FOLDER'] = 'workshopFiles/'
app.config['ROOT_FOLDER'] = '../'
app.config['MAX_CONTENT_LENGTH'] = 512 * 1024 * 1024     # 512 MB
app.config['ALLOWED_EXTENSIONS'] = ['.mp4']

@app.route('/')
def index():
    return redirect( url_for('user.loginGet') )
 
app.register_blueprint(user, url_prefix='/user')
app.register_blueprint(workshop, url_prefix='/workshop')

@app.route('/serve-file/<fileDirectory>/<fileName>', methods=['GET'])
def display_files(fileDirectory, fileName):
    # filePath = fileDirectory + '/' + fileName
    return send_from_directory( f'../{fileDirectory}', fileName, as_attachment=True)

if __name__ == "__main__":
    # app.run(debug=True, port = 5555)
    app.run(host='0.0.0.0',port=5555, debug=True)

module/app.py
from flask import Flask

app = Flask(__name__, template_folder='../templates', static_folder='../static')

module/auth.py
from module.app import app
from flask_jwt_extended import JWTManager

app.config["JWT_TOKEN_LOCATION"] = ["cookies"]
app.config['JWT_SECRET_KEY'] = 'secret'
app.config["JWT_COOKIE_SECURE"] = False

jwt = JWTManager(app)

templates/edit_subtitles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Page</title>
    <link rel="stylesheet" href="/static/styleForEdit.css">
</head>
<body>
    <div class="video-section">
        {% set filePath = videoPath.split('/') %}
        {% set fileDirectory = filePath[0] %}
        {% set fileName = filePath[1] %}
        <video src="{{ url_for('display_files', fileDirectory=fileDirectory, fileName=fileName) }}" controls preload="preload"></video>
    </div>
    <form id="form" action="/workshop/update-subtitles", method="POST">
        {% for line in lines %}
        <div class="line-card">
            <p>
                {{line[1]}}
            </p>
            <p>
                lines: 
                <input class="singleLines" type="text" name="{{loop.index}}" value="{{line[2]}}" style="width: 30rem">
            </p>
        </div>
        {% endfor %}
        <button type="submit">Create</button>
    </form>
    <script>
        const formNode = document.getElementById('form')
        formNode.addEventListener('submit', updateSubtitle)
        
        async function updateSubtitle(e){
            e.preventDefault();
            const videoNode = document.querySelector("body > div > video").src
            const videoPath = videoNode.slice(38)
            const formData = new FormData(formNode)
            formData.append('video_path', videoPath)
            await fetch('/workshop/update-subtitles', fetchOptions(formData))
            return location.assign('http://54.226.246.195:5555/workshop')
        }
        const fetchOptions = (argPutInBody) => {
            return {
                method: 'post',
                // credentials: 'same-origin',
                // headers: {
                //     'X-CSRF-TOKEN': getCookie('csrf_access_token'),
                // },
            body: argPutInBody,
            }
        }
    </script>
</body>
</html>

templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>Login Page</h2>
    {% if msg %}
    <p>{{msg}}</p>
    {% endif %}
    <form id="form-section">
        <p>Email:</p>
        <input type="email" name="user_email" required> 
        <p>Password:</p>
        <input type="password" name="user_password" required>
        <button type="submit" id="submitBtn">Login</button>
    </form>
    <br>
    <a href="{{url_for('user.registerGet')}}"> Go SignUP</a>
    <script>

        const formSection = document.getElementById('form-section');
        formSection.addEventListener('submit', login)

        async function login(e) {
            e.preventDefault();
            const formData = new FormData(formSection)
            const response = await fetch('/user/login', fetchOptions(formData));
            const result = await response.json();    
            if( result.msg === 'login successful' )
                return location.assign('http://54.226.246.195:5555/workshop')
            else 
                return location.href = `http://54.226.246.195:5555//user/login?msg=${result.msg}`;
        }
        
        const fetchOptions = (argPutInBody) => {
            return {
                method: 'post',
                body: argPutInBody,
            }
        }
        </script>
</body>
</html>

templates/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h2>Register Page</h2>
    {% if msg %}
    <p>{{msg}}</p>
    {% endif %}
    <form id="form-section">
        <p>Email:</p>
        <input type="email" name="email">
        <p>Password:</p>
        <input type="password" name="password">
        <button type="submit">SignUP</button>
    </form>
    <br>
    <a href="{{url_for('user.loginGet')}}">Already signUp</a>
    <script>
        const formSection = document.getElementById('form-section');
        formSection.addEventListener('submit', register)

        async function register(e) {
            e.preventDefault();
            
            const formData = new FormData(formSection)
            const response = await fetch('/user/register', fetchOptions(formData));
            const result = await response.json();
            if( result.msg === 'Register successfully' )
                return location.assign('http://54.226.246.195:5555/user/login')
            else
                return location.href = `http://54.226.246.195:5555/user/register?msg=${result.msg}`;
        }

        const fetchOptions = (argPutInBody) => {
            return {
                method: 'post',
                body: argPutInBody,
            }
        }
    </script>
</body>
</html>

templates/workshop_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Upload</title>
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
</head>
<body>
    <div class="app">
        <div class="form-section">
            <form action="{{url_for('workshop.upload')}}" id="upload-section" method="POST" enctype="multipart/form-data">
                <input type="file" id="file" name="file_from_user" accept="video/mp4" required>
                <input type="submit" value="Upload">
            </form>
            <br>
            <br>
            <form class="downloadBTN">
                <input type="submit" name="" value="Download Test File">
            </form>
        </div>
        <div class="files-section" id="unsubtitle-section">
            <h3 style="margin: 1rem auto;">Un-subtitled File</h3>
            {% for user_video in user_videos %}
                {% set filePath = user_video[0].split('/') %}
                {% set fileDirectory = filePath[0] %}
                {% set fileName = filePath[1] %}
                {% set srtExist = user_video[1] %}
                <div class="single-video">
                    <video src="{{ url_for('display_files', fileDirectory=fileDirectory, fileName=fileName) }}" controls preload="preload"></video>
                    {% if srtExist %}
                        <form action="{{ url_for('workshop.add_subtitles') }}" class="add-button" method="POST">
                            <input type="submit" name="generate-subtitles" value="Edit Subtitles">
                        </form>
                        <form action="{{ url_for('workshop.merge_subtitles') }}" class="merge-button" id="mergeButton" method="POST">
                            <input type="submit" name="merge-subtitles" value="Merge Subtitles">
                        </form>
                    {% else %}
                        <form action="{{ url_for('workshop.add_subtitles') }}" class="add-button" method="POST">
                            <input type="submit" name="generate-subtitles" value="Create Subtitles">
                        </form>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div class="files-section" id="subtitle-section">
            <h3 style="margin: 1rem auto;">Subtitled File</h3>
            {% for workshop_video in workshop_videos %}
                {% set filePath1 = workshop_video[0].split('/') %}
                {% set fileDirectory1 = filePath1[0] %}
                {% set fileName1 = filePath1[1] %}
                <div class="single-video">
                    <video src="{{ url_for('display_files', fileDirectory=fileDirectory1, fileName=fileName1) }}" controls preload="preload"></video>
                    <!-- <form action="{{ url_for('workshop.add_subtitles') }}" class="update-button" method="POST">
                        <input type="submit" name="generate-subtitles" value="Update Subtitles">
                    </form>
                    <form action="{{ url_for('workshop.merge_subtitles') }}" class="merge-button" id="mergeButton" method="POST">
                        <input type="submit" name="merge-subtitles" value="Merge Subtitles">
                    </form> -->
                    <form class="downloadBTN">
                        <input type="submit" value="Download Video">
                    </form>
                    <form class="downloadBTN">
                        <input type="submit" value="Download Srt">
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
    <form id="logout" action="/logout" method="POST">
        <button type="submit">Logout</button>
    </form>
    <script>
        const uploadSection = document.getElementById('upload-section')
        uploadSection.addEventListener('submit', upload)
        
        const unsubSection = document.getElementById('unsubtitle-section')
        unsubSection.addEventListener('submit', createSubtitle)
        unsubSection.addEventListener('submit', mergeSubtitle)
        
        // const subSection = document.getElementById('subtitle-section')
        // subSection.addEventListener('submit', updateSubtitle)
        // subSection.addEventListener('submit', mergeSubtitle)

        const logoutSection = document.getElementById('logout')
        logoutSection.addEventListener('submit', logout)

        const downloadSection = document.querySelectorAll('.downloadBTN')
        for(let i=0; i < downloadSection.length ; i++){
            downloadSection[i].addEventListener('submit', download)
        }
        // downloadSection.addEventListener('submit', async (e) => {
        //     e.preventDefault()
        //     console.log(e.target.value)
        //     return location.assign('http://54.226.246.195:5555/serve-file/testFile/test_video.mp4')
        // })
        
        async function download(e){
            e.preventDefault()
            swither = e.target.querySelector('input').value
            if(swither == "Download Test File")
                return location.assign('http://54.226.246.195:5555/serve-file/testFile/test_video.mp4')
            else if(swither == "Download Video"){
                videoPath = e.target.parentNode.querySelector('video').src
                return location.assign(videoPath)
            }
            else if(swither == 'Download Srt'){
                videoPath = e.target.parentNode.querySelector('video').src
                srtPath = videoPath.replace('/workshopFiles', '/srtFiles')
                srtPath = srtPath.replace('.mp4', '.srt')
                console.log(srtPath)
                return location.assign(srtPath)
            }
        }

        async function upload(e){
            e.preventDefault();
            const userFile = document.getElementById('file').files[0];
            const formData = new FormData();
            formData.append('file_from_user', userFile)
            const response = await fetch('http://54.226.246.195:5555/workshop/upload-video', fetchOptions(formData));
            const result = await response.json()
            if(result.msg == 'Upload successfully')
                return location.reload()

        }

        async function createSubtitle(e){
            e.preventDefault();
            if (e.target.className == 'merge-button')
                return ;
            videoName = e.target.parentNode.querySelector('video').src
            video_path = videoName.slice(38)
            const response = await fetch('http://54.226.246.195:5555/workshop/add-subtitles', fetchOptions(JSON.stringify(video_path)));
            const result = await response.json()
            return window.location.href = `http://54.226.246.195:5555/workshop/edit-subtitles/${video_path}`;
        }

        async function mergeSubtitle(e){
            e.preventDefault();
            console.log(e.target.className)
            if (e.target.className == 'add-button' | e.target.className == 'update-button')
                return ;
            videoName = e.target.parentNode.querySelector('video').src
            video_path = videoName.slice(38)
            await fetch('http://54.226.246.195:5555/workshop/merge-subtitles', fetchOptions(JSON.stringify(video_path)));
            // const result = await response.json()
            return window.location.href = `http://54.226.246.195:5555/workshop`;
            // return;
        }

        async function updateSubtitle(e){
            e.preventDefault();
            console.log(e.target.className)
            if (e.target.className == 'merge-button')
                return ;
            videoName = e.target.parentNode.querySelector('video').src
            video_path = videoName.slice(38)
            // const response = await fetch('http://54.226.246.195:5555/workshop/update-subtitles', fetchOptions(JSON.stringify(video_path)));
            // const result = await response.json()
            return window.location.href = `http://54.226.246.195:5555/workshop/edit-subtitles/${video_path}`;
        }

        async function logout(e){
            e.preventDefault();
            const response = await fetch('http://54.226.246.195:5555/logout', {method: "POST"});
            return location.assign('http://54.226.246.195:5555')
        }

        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2)
                return parts.pop().split(';').shift();
        }
        const fetchOptions = (argPutInBody) => {
            return {
                method: 'post',
                credentials: 'same-origin',
                headers: {
                    'X-CSRF-TOKEN': getCookie('csrf_access_token'),
                },
            body: argPutInBody,
            }
        }
        </script>
</body>
</html>